### ISSUE TITLE
[BUG] HelloWorldSkill skill will not load from default projen genrated template

### ISSUE THREAD

**Issue by rosskouk** [mikejgray/ovos-skill-projen#14]
### Description

When trying to begin skill development with Neon.AI I used projen to create a template.  This template contains a default HelloWorldSkill class.  I wanted to get this running on a Neon.AI instance running on Docker containers.  The containers were build using the docker-compose file from the NeonCore repo here: https://github.com/NeonGeckoCom/NeonCore/blob/23.12.20/docker/docker-compose.yml.

The local skill folder is then mounted into the neon-skills container via the NEON_SKILLS_DIR environment variable.

### Steps to Reproduce

- Create a new folder
- run `projen new ovosskill --from "@mikejgray/ovos-skill-projen"`
- Edit `.projenrc.json` and add the following:
  ```
  "repositoryUrl": "https://github.com/rosskouk/AskNeonNavidrome",
  "skillClass": "HelloWorldSkill",
  "author": "Name Here",
  "authorAddress": "xxxx@gmail.com",
  "license": "MIT"
  ```
- run `pj`
- Create a repository on GitHub for the skill and add it as a remote the the existing Git repository created when projen was run
- Push all files and allow skill.json to be created by the GH actions scripts
- Pull the repo to download a local copy of the skills.json file.
- Start the Neon.AI Docker containers.
- At this point the skill fails to load.

### Relevant Code

```
2023-12-29 16:42:55.350 - skills - ovos_workshop.skill_launcher:load:295 - INFO - ATTEMPTING TO LOAD SKILL: AskNeonNavidrome
2023-12-29 16:42:55.351 - skills - ovos_workshop.skill_launcher:_load_skill_source:428 - ERROR - Failed to load AskNeonNavidrome due to a missing file.
2023-12-29 16:42:55.352 - skills - ovos_workshop.skill_launcher:_create_skill_instance:456 - WARNING - Skill load raised exception: Expected module and got None
2023-12-29 16:42:55.353 - skills - ovos_workshop.skill_launcher:_create_skill_instance:476 - WARNING - Legacy skill: 'NoneType' object is not callable
2023-12-29 16:42:55.354 - skills - mycroft.skills.skill_manager:_load_skill:624 - ERROR - Load of skill /skills/AskNeonNavidrome failed!
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/ovos_workshop/skill_launcher.py", line 472, in _create_skill_instance
    self.instance = skill_creator(bus=self.bus,
TypeError: 'NoneType' object is not callable


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mycroft/skills/skill_manager.py", line 622, in _load_skill
    load_status = skill_loader.load()
  File "/usr/local/lib/python3.8/site-packages/ovos_workshop/skill_launcher.py", line 296, in load
    return self._load()
  File "/usr/local/lib/python3.8/site-packages/ovos_workshop/skill_launcher.py", line 378, in _load
    self.loaded = self._create_skill_instance()
  File "/usr/local/lib/python3.8/site-packages/ovos_workshop/skill_launcher.py", line 477, in _create_skill_instance
    self.instance = skill_creator()
TypeError: 'NoneType' object is not callable
```

**Comment by mikejgray** [comment]
@rosskouk Apologies for getting back to you late on this, would you please update your version and try again? I think I've addressed the issues at play here, at least based on my local testing.

**Comment by rosskouk** [comment]
Thanks Mike, will do.

**Comment by mikejgray** [comment]
@rosskouk I'm going to close this issue as resolved, but please reopen if you find the update didn't fix your problem

**Comment by rosskouk** [comment]
Thanks Mike.  Apologies for not being in touch sooner, I've not been able
to get to it as of yet.
